/**
 * biblaOp — Open Protocol Library
 * Shared protocol constants: relay functions, digital inputs, and error codes.
 */

/** Relay function options — maps relay function number to name and tracking flag */
export const RELAY_FUNCTION_OPTIONS: { value: string; label: string; tracking?: boolean }[] = [
  { value: '000', label: '000 - Off' },
  { value: '001', label: '001 - OK', tracking: false },
  { value: '002', label: '002 - NOK', tracking: false },
  { value: '003', label: '003 - Low', tracking: false },
  { value: '004', label: '004 - High', tracking: false },
  { value: '005', label: '005 - Low Torque', tracking: false },
  { value: '006', label: '006 - High Torque', tracking: false },
  { value: '007', label: '007 - Low Angle', tracking: false },
  { value: '008', label: '008 - High Angle', tracking: false },
  { value: '009', label: '009 - Cycle Complete', tracking: true },
  { value: '010', label: '010 - Alarm', tracking: true },
  { value: '011', label: '011 - Batch NxOK', tracking: false },
  { value: '012', label: '012 - Job OK', tracking: false },
  { value: '013', label: '013 - Job NOK', tracking: false },
  { value: '014', label: '014 - Job Running', tracking: true },
  { value: '015', label: '015 - Car is Done', tracking: false },
  { value: '016', label: '016 - Car is Done Status OK', tracking: false },
  { value: '017', label: '017 - Tool Health OK', tracking: true },
  { value: '018', label: '018 - Power Focus Ready', tracking: true },
  { value: '019', label: '019 - Tool Ready', tracking: true },
  { value: '020', label: '020 - Tool Start Switch', tracking: true },
  { value: '021', label: '021 - Dir. Switch = CW', tracking: true },
  { value: '022', label: '022 - Dir. Switch = CCW', tracking: true },
  { value: '023', label: '023 - Tightening Direction CCW', tracking: false },
  { value: '024', label: '024 - Tool Tightening', tracking: true },
  { value: '025', label: '025 - Tool Loosening', tracking: true },
  { value: '026', label: '026 - Tool Running', tracking: true },
  { value: '027', label: '027 - Tool Running CW', tracking: true },
  { value: '028', label: '028 - Tool Running CCW', tracking: true },
  { value: '029', label: '029 - Statistic Alarm', tracking: false },
  { value: '030', label: '030 - Tool Locked', tracking: true },
];

/** Digital input function options */
export const DIGITAL_INPUT_OPTIONS: { value: string; label: string }[] = [
  { value: '000', label: '000 - Off' },
  { value: '001', label: '001 - Select Pset Bit 0' },
  { value: '002', label: '002 - Select Pset Bit 1' },
  { value: '003', label: '003 - Select Pset Bit 2' },
  { value: '004', label: '004 - Select Pset Bit 3' },
  { value: '005', label: '005 - Tightening Interlock' },
  { value: '006', label: '006 - Reset Batch' },
  { value: '007', label: '007 - Unlock Tool' },
  { value: '008', label: '008 - External Start' },
  { value: '009', label: '009 - Reverse' },
  { value: '010', label: '010 - Abort' },
];

/** MID 0004 error code descriptions */
export const ERROR_CODES: Record<string, string> = {
  '00': 'No error',
  '01': 'Invalid data',
  '02': 'Pset ID not present',
  '03': 'Pset can not be set',
  '04': 'Pset not running',
  '06': 'Job ID not present',
  '07': 'Job info not present',
  '08': 'Job can not be set',
  '09': 'Job not running',
  '10': 'Job batch decrement failed',
  '11': 'Not possible to create Pset',
  '12': 'Programming control not granted',
  '13': 'Controller is not a sync Master',
  '14': 'Multi-spindle status not OK',
  '17': 'Revision upgrade required',
  '20': 'Calibration failed',
  '21': 'Subscription already exists',
  '22': 'Subscription does not exist',
  '23': 'Subscription not supported',
  '24': 'Command does not support rev',
  '25': 'MID revision unsupported',
  '30': 'Controller not ready',
  '31': 'Pairing failed',
  '40': 'Client already connected',
  '41': 'Reject request, power up in progress',
  '50': 'VIN upload subscription exists',
  '51': 'VIN upload subscription does not exist',
  '52': 'VIN input source not granted',
  '53': 'Last tightening result subscription exists',
  '54': 'Last tightening result subscription does not exist',
  '55': 'Alarm subscription already exists',
  '56': 'Alarm subscription does not exist',
  '58': 'Pset subscription already exists',
  '59': 'Pset subscription does not exist',
  '60': 'Job info subscription already exists',
  '61': 'Job info subscription does not exist',
  '62': 'Job line control info subscription exists',
  '63': 'Job line control info subscription does not exist',
  '64': 'Controller not sync master',
  '65': 'Multi-spindle result subscription already exists',
  '66': 'Multi-spindle result subscription does not exist',
  '67': 'Job line control alert 1 subscription exists',
  '68': 'Job line control alert 1 subscription does not exist',
  '69': 'Job line control alert 2 subscription exists',
  '70': 'Job line control alert 2 subscription does not exist',
  '71': 'Controller type subscription already exists',
  '72': 'Controller type subscription does not exist',
  '73': 'Multi-spindle status subscription exists',
  '74': 'Multi-spindle status subscription does not exist',
  '76': 'Open Protocol commands disabled',
  '77': 'Open Protocol commands disabled subscription exists',
  '78': 'Open Protocol commands disabled subscription does not exist',
  '79': 'Motor tuning result subscription already exists',
  '80': 'Motor tuning result subscription does not exist',
  '81': 'Selector socket info subscription exists',
  '82': 'Selector socket info subscription does not exist',
  '83': 'Digin info subscription already exists',
  '84': 'Digin info subscription does not exist',
  '85': 'Lock at batch done subscription already exists',
  '86': 'Lock at batch done subscription does not exist',
  '87': 'Open Protocol commands disabled (digital input)',
  '88': 'Open Protocol commands disabled (fieldbus)',
  '89': 'Open Protocol commands disabled (soft PLC)',
  '90': 'No alarm present',
  '91': 'Tool tag id unknown',
  '92': 'Tool tag subscription already exists',
  '93': 'Tool tag subscription does not exist',
  '94': 'Not allowed to set or reset this digital output',
  '95': 'HVO button subscription already exists',
  '96': 'HVO button subscription does not exist',
  '97': 'Not a Power Focus',
  '98': 'Generic subscription already exists',
  '99': 'Generic subscription does not exist',
};
